# Generated by Django 4.2.6 on 2023-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_forgotten_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='forgotten_token',
            field=models.CharField(blank=True, default='', max_length=36, null=True, unique=True),
        ),
    ]
