# Generated by Django 4.2.6 on 2023-11-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
